name: Lint Python Code

on:
  pull_request:
    paths:
      - "**/*.py"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x" # Choose the Python version you want to use

      - name: Install dependencies
        run: pip install pylint

      - name: Lint code
        run: pylint ./main.py

      - name: Check for changes
        id: check_changes
        run: git diff --exit-code

      - name: Set status check
        if: steps.check_changes.outputs.exit_code == 1
        run: echo "Linting failed, please check and fix the issues." && exit 1
